"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./client/auth.routes"));
const admin_users_routes_1 = __importDefault(require("./admin/admin.users.routes"));
const admin_restaurant_routes_1 = __importDefault(require("./admin/admin.restaurant.routes"));
const admin_plans_routes_1 = __importDefault(require("./admin/admin.plans.routes"));
const admin_subscription_routes_1 = __importDefault(require("./admin/admin.subscription.routes"));
const account_routes_1 = __importDefault(require("./client/account.routes"));
const balances_route_1 = __importDefault(require("./client/balances.route"));
const menu_client_routes_1 = __importDefault(require("./client/menu.client.routes"));
const restaurant_ad_routes_1 = __importDefault(require("./restaurant/restaurant.ad.routes"));
const menu_restaurant_routes_1 = __importDefault(require("./restaurant/menu.restaurant.routes"));
const restaurant_account_routes_1 = __importDefault(require("./restaurant/restaurant.account.routes"));
const restaurant_packages_routes_1 = __importDefault(require("./restaurant/restaurant.packages.routes"));
const restaurant_group_routes_1 = __importDefault(require("./restaurant/restaurant.group.routes"));
const firebase_routes_1 = __importDefault(require("./common/firebase.routes"));
const ads_routes_1 = __importDefault(require("./common/ads.routes"));
const notification_routes_1 = __importDefault(require("./common/notification.routes"));
const router = (0, express_1.Router)();
router.use('/auth', auth_routes_1.default);
router.use('/admin/users', admin_users_routes_1.default);
router.use('/admin/restaurants', admin_restaurant_routes_1.default);
router.use('/admin/plans', admin_plans_routes_1.default);
router.use('/admin/subscriptions', admin_subscription_routes_1.default);
router.use('/client/account', account_routes_1.default);
router.use('/client/balance', balances_route_1.default);
router.use('/client/menu', menu_client_routes_1.default);
router.use('/restaurants/ads', restaurant_ad_routes_1.default);
router.use('/restaurants/menu', menu_restaurant_routes_1.default);
router.use('/restaurants/account', restaurant_account_routes_1.default);
router.use('/restaurants', restaurant_packages_routes_1.default);
router.use('/groups', restaurant_group_routes_1.default);
router.use('/ads', ads_routes_1.default);
router.use('/firebase', firebase_routes_1.default);
router.use('/notifications', notification_routes_1.default);
exports.default = router;
//# sourceMappingURL=index.js.map