import { Router } from 'express';
import authRoutes from './client/auth.routes';
import usersRoutes from './admin/admin.users.routes';
import adminRestaurantsRoutes from './admin/admin.restaurant.routes';
import adminPlansRoutes from './admin/admin.plans.routes';
import subscriptionsRoutes from './admin/admin.subscription.routes';
import adminInvoicesRoutes from './admin/invoices.routes';
import adminOverviewRoutes from './admin/overview.routes';
import accountRoutes from './client/account.routes';
import balanceRoutes from './client/balances.route';
import clientMenuRoutes from './client/menu.client.routes';
import clientOrderRoutes from './client/order.routes';
import adsRestaurantsRoutes from './restaurant/restaurant.ad.routes';
import restaurantOrdersRoutes from './restaurant/orders.routes';
import tablesRoutes from './restaurant/tables.routes';
import menuRoutes from './restaurant/menu.restaurant.routes';
import kitchenSectionsRoutes from './restaurant/kitchen-sections.routes';
import restaurantAccountRoutes from './restaurant/restaurant.account.routes';
import packagesRoutes from './restaurant/restaurant.packages.routes';
import restaurantSubscriptionRoutes from './restaurant/restaurant.subscription.routes';
import restaurantInvoicesRoutes from './restaurant/restaurant.invoices.routes';
import restaurantOverviewRoutes from './restaurant/restaurant.overview.routes';
import qrScansRoutes from './restaurant/qr-scans.routes';
import paymentsRoutes from './restaurant/payments.routes';
import groupsRoutes from './restaurant/restaurant.group.routes';
import firebaseRoutes from './common/firebase.routes';
import adscommonRoutes from './common/ads.routes';
import notificationsRoutes from './common/notification.routes';
import uploadRoutes from './common/upload.routes';
import plansRoutes from './common/plans.routes';
import restaurantsRoutes from './common/restaurants.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/admin/users', usersRoutes);
router.use('/admin/restaurants', adminRestaurantsRoutes);
router.use('/admin/plans', adminPlansRoutes);
router.use('/admin/subscriptions', subscriptionsRoutes);
router.use('/admin/invoices', adminInvoicesRoutes);
router.use('/admin/overview', adminOverviewRoutes);
router.use('/client/account', accountRoutes);
router.use('/client/balance', balanceRoutes);
router.use('/customer/menu', clientMenuRoutes);
router.use('/customer/orders', clientOrderRoutes);
// Specific restaurant routes (must come BEFORE public routes to avoid conflicts)
router.use('/restaurants/ads', adsRestaurantsRoutes);
router.use('/restaurants/menu', menuRoutes);
router.use('/restaurants/kitchen-sections', kitchenSectionsRoutes);
router.use('/restaurants/account', restaurantAccountRoutes);
router.use('/restaurants/subscription', restaurantSubscriptionRoutes);
router.use('/restaurants/invoices', restaurantInvoicesRoutes);
router.use('/restaurants/overview', restaurantOverviewRoutes);
router.use('/restaurants/qr-scans', qrScansRoutes);
router.use('/restaurants/payments', paymentsRoutes);
router.use('/restaurants/packages', packagesRoutes);
router.use('/restaurants/balance', packagesRoutes);
router.use('/restaurants/orders', restaurantOrdersRoutes);
router.use('/restaurants/tables', tablesRoutes);
// Public restaurants routes - must be LAST to avoid route conflicts
router.use('/restaurants', restaurantsRoutes);
router.use('/groups', groupsRoutes);
router.use('/ads', adscommonRoutes);
router.use('/firebase', firebaseRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/uploadFile', uploadRoutes);
router.use('/plans', plansRoutes);
export default router;
